services:
    simpleVtuApp.papercut:
        image: changemakerstudiosus/papercut-smtp:latest
        container_name: simpleVtuApp-papercut
        ports:
            - 8080:80
            - 25:25

    simpleVtuApp.seq:
        image: datalust/seq:latest
        container_name: simpleVtuApp-seq
        volumes:
          - ./.containers/seq:/data
        environment:
            - ACCEPT_EULA=Y
        ports:
          - 5341:5341
          - 8081:80

    simpleVtuApp.queue:
        image: masstransit/rabbitmq:latest
        container_name: simpleVtuApp-queue
        hostname: simpleVtuApp-queue-host
        volumes:
            - ./.containers/queue/data/:/var/lib/rabbitmq
            - ./.containers/queue/log/:/var/log/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672

    simpleVtuApp.redis:  
        image: redis:latest
        container_name: simpleVtuApp-redis
        command: redis-server /usr/local/etc/redis/redis.conf --save 60 1 --appendonly yes --loglevel warning
        restart: unless-stopped
        volumes:
          - ./redis/dаta:/data
          - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
          - "6379:6379"
        healthcheck:
          test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        environment:
          - REDIS_PORT=6379
          - REDIS_DATABASES=16
          - REDISTIMESERIES_ARGS=RETENTION_POLICY=20
          - REDIS_ARGS=--notify-keyspace-events Ksg

    redis-insight:
        image: redis/redisinsight:latest
        container_name: simpleVtuApp-insight
        restart: always
        ports:
          - "5540:5540"
        volumes:
          - ./redis/insight:/data
