services:
    simpleVtuApp.papercut:
        image: changemakerstudiosus/papercut-smtp:latest
        container_name: simpleVtuApp-papercut
        ports:
            - 8080:80
            - 25:25

    simpleVtuApp.seq:
        image: datalust/seq:latest
        container_name: simpleVtuApp-seq
        volumes:
          - ./.containers/seq:/data
        environment:
            - ACCEPT_EULA=Y
        ports:
          - 5341:5341
          - 8081:80

    simpleVtuApp.queue:
        image: masstransit/rabbitmq:latest
        container_name: simpleVtuApp-queue
        hostname: simpleVtuApp-queue-host
        volumes:
            - ./.containers/queue/data/:/var/lib/rabbitmq
            - ./.containers/queue/log/:/var/log/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672

    simpleVtuApp.redis:  
        image: redis:latest
        container_name: simpleVtuApp-redis
        command: redis-server /usr/local/etc/redis/redis.conf --save 60 1 --appendonly yes --loglevel warning
        restart: unless-stopped
        volumes:
          - ./redis/dаta:/data
          - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
        ports:
          - "6379:6379"
        healthcheck:
          test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
        environment:
          - REDIS_PORT=6379
          - REDIS_DATABASES=16
          - REDISTIMESERIES_ARGS=RETENTION_POLICY=20
          - REDIS_ARGS=--notify-keyspace-events Ksg

    redis-insight:
        image: redis/redisinsight:latest
        container_name: simpleVtuApp-insight
        restart: always
        ports:
          - "5540:5540"
        volumes:
          - ./redis/insight:/data

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        container_name: simpleVtuApp-elasticsearch
        environment:
          - xpack.security.enabled=false
          - discovery.type=single-node
          # - xpack.monitoring.enabled=true  if enabled, use default credentials to log in to kibana: user: elastic    password: changeme
          # - xpack.watcher.enabled=false
          # - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ports:
          - 9200:9200
        volumes:
          - elasticsearch-data:/usr/share/elasticsearch/data
        networks:
          - elasticsearch-network

    kibana:
        image: docker.elastic.co/kibana/kibana:8.13.4
        container_name: simpleVtuApp-kibana
        ports:
          - 5601:5601
        # depeds_on:
        #   - elasticsearch
        environment:
          - ELASTICSEARCH_URL=http://elasticsearch:9200
          # - ELASTICSEARCH_URL=http://localhost:9200
        networks:
          - elasticsearch-network

volumes:
    elasticsearch-data:
        driver: local

networks:
    elasticsearch-network:
        driver: bridge
